### ISSUE TITLE
[BUG] [Stack Preview Antifocus] Clicking on spoilers while creating/editing a post does not reveal the spoiler

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [CertainPerformance/Stack-Exchange-Userscripts#15]
**Which userscript**
Stack Preview Antifocus

**Describe the bug**
When trying to create/edit a post with spoilers with this userscript enabled, clicking the spoiler to reveal it no longer works.

**To Reproduce**
1. On the URL '[https://meta.stackexchange.com/posts/71396/edit](https://meta.stackexchange.com/posts/71396/edit)'
2. Click on the spoiler.
3. It does not reveal.

**Expected behavior**
Clicking the spoiler should reveal it (works when the userscript is disabled).

**Environment:**
 - OS: Windows 10 x64 2004.
 - Browser: Chrome.
 - Browser Version: 86.0.4240.193
 - Userscript Manager: Tampermonkey.

**Comment by Ahmed-Abdelhameed** [comment]
I replaced the `if` condtion from:

```
!e.target.matches('.edit-snippet')
```
to:
```
!e.target.matches('.edit-snippet,.spoiler')
```
..and it fixed the problem. However, the textarea is back to stealing the focus. I'm not sure if there's a better solution. That is good enough for me though (and spoilers aren't very common on most SE sites, anyway).

**Comment by CertainPerformance** [comment]
Good catch, thanks. Just had to separate out the snippet vs spoiler click logic.

**Comment by Ahmed-Abdelhameed** [comment]
Thanks for the quick fix. Your solution is obviously much better than mine. I confirm that it works perfectly now.
