### ISSUE TITLE
[BUG] [Stack Highlight Unfolded Comments] Incompatible with the Threaded Comments userscript

### ISSUE THREAD

**Issue by PurpleMagick** [CertainPerformance/Stack-Exchange-Userscripts#9]
**Which userscript**
Stack Highlight Unfolded Comments

**Describe the bug**
When using the Threaded Comments userscrpt from [here](https://stackapps.com/questions/2050/threaded-comments) the comments that were already shown are unthreaded.

**To Reproduce**
Steps to reproduce the behavior using both usesrcripts:
1. On the URL https://meta.stackoverflow.com/questions/394798/if-this-isn-t-a-low-quality-question-how-low-would-quality-have-to-be
2. Observe the comments being indented.

[![Indented comments][1]][1]

3. Click **show X more comments** 
4. Scroll back up and observe the old comment now being flat, while new comments are indented where they would normally should be.

[![Comments without indentation][2]][2]

**Expected behavior**
After loading the highlight for new comments should be preserved but also the nesting

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 74 
 - Userscript Manager: Greasemonkey

**Additional context**
I tracked down the problem to two lines in Stack Highlight Unfolded Comments

```js
comment.children[0].removeAttribute('style');
comment.children[1].removeAttribute('style');
```

Removing these lines makes the behaviour correct:

[![Comments indented and highlighted][3]][3]

Both userscripts change the `style` directly on comments, the threaded comments script does it to add `margin-left` for the indentation. 

I would need to investigate more for a better fix. I assume the `style` attribute is removed to drop the highlight after a subsequent reload. If that's all that's needed, then perhaps only the `backgroundColor` can be wiped. Or the opposite - maybe only the `margin-left` needs to be preserved.

  [1]:  https://i.imgur.com/hYbHwfV.png
  [2]:  https://i.imgur.com/nCnYh2b.png
  [3]:  https://i.imgur.com/UWhG92r.png

**Comment by CertainPerformance** [comment]
It's a simple tweak. When new comments get clicked on and get displayed, prior highlighted comments needed to have their highlight removed, which I wanted to do without the empty `style` attributes remaining in the DOM. But if other scripts set `style` properties directly, the highlight needs to be removed with `removeProperty` instead of the whole `style` being removed.
